### PR TITLE
Up to section 4.

### PR DESCRIPTION
**Pull request by wouter-swierstra**
I'm up to section 4. Processing final comments now.

### CODE REVIEW

**Comment by wouter-swierstra** [comment]
I know it's annoying, but you should probably run a spellchecker before submitting.

**Comment by phile314** [comment]
Will do the spell-checking before submitting. Btw, I guess you don't mind if I send it to the reading club ML after its submitted?

**Comment by wouter-swierstra** [comment]
No problem. I haven't sent anything to the reading club list yet. Just send
it off tomorrow at your leisure.

**Comment by wouter-swierstra** [comment]
Hi @phile314, I've pushed all my comments and changes. If you have any specific questions, don't hesitate to ask!

Good luck with the submission and speak to you soon!

**Pull request merged**
